FROM ghcr.io/puppeteer/puppeteer:latest

USER root

# ENV PUPPETEER_SKIP_DOWNLOAD=true

RUN sed -i 's|http://deb.debian.org|https://mirrors.tuna.tsinghua.edu.cn|g' /etc/apt/sources.list.d/*.sources \
 && sed -i 's|http://security.debian.org|https://mirrors.tuna.tsinghua.edu.cn/debian-security|g' /etc/apt/sources.list.d/*.sources || true

RUN apt-get update && \
    apt-get install -y ffmpeg
# RUN apt-get install -y chromium --no-install-recommends
# RUN apt-get clean && rm -rf /var/lib/apt/lists/*

USER pptruser

WORKDIR /home/pptruser/myapp

COPY package*.json ./

RUN npm config set registry https://registry.npmmirror.com && npm i --omit=dev

COPY . .

RUN mkdir -p /home/pptruser/output /home/pptruser/tmp/render

ENV NODE_ENV=production

ENTRYPOINT ["node", "index.js"]